MagicVilla_API-master/MagicVilla_Web/Controllers/VillaNumberController.cs
using AutoMapper;
using MagicVilla_Utility;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.Dto;
using MagicVilla_Web.Models.VM;
using MagicVilla_Web.Services;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Data;

namespace MagicVilla_Web.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IVillaNumberService _villaNumberService;
        private readonly IVillaService _villaService;
        private readonly IMapper _mapper;
        public VillaNumberController(IVillaNumberService villaNumberService, IMapper mapper, IVillaService villaService)
        {
            _villaNumberService = villaNumberService;
            _mapper = mapper;
            _villaService = villaService;
        }

        public async Task<IActionResult> IndexVillaNumber()
        {
            List<VillaNumberDTO> list = new();

            var response = await _villaNumberService.GetAllAsync<APIResponse>(await HttpContext.GetTokenAsync("access_token"));
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<VillaNumberDTO>>(Convert.ToString(response.Result));
}
            return View(list);
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateVillaNumber()
        {
            VillaNumberCreateVM villaNumberVM = new();
            var response = await _villaService.GetAllAsync<APIResponse>(await HttpContext.GetTokenAsync("access_token"));
            if (response != null && response.IsSuccess)
{
                villaNumberVM.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>
                    (Convert.ToString(response.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    }); ;
            }
            return View(villaNumberVM);
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateVillaNumber(VillaNumberCreateVM model)
        {
            if (ModelState.IsValid)
            {

                var response = await _villaNumberService.CreateAsync<APIResponse>(model.VillaNumber, await HttpContext.GetTokenAsync("access_token"));
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexVillaNumber));
                }
                else
                {
                    if (response.ErrorMessages.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                    }
                }
            }

            var resp = await _villaService.GetAllAsync<APIResponse>(await HttpContext.GetTokenAsync("access_token"));
            if (resp != null && resp.IsSuccess)
            {
                model.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>
                    (Convert.ToString(resp.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    }); ;
            }
            return View(model);
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateVillaNumber(int villaNo)
        {
            VillaNumberUpdateVM villaNumberVM = new();
            var response = await _villaNumberService.GetAsync<APIResponse>(villaNo, await HttpContext.GetTokenAsync("access_token"));
            if (response != null && response.IsSuccess)
            {
                VillaNumberDTO model = JsonConvert.DeserializeObject<VillaNumberDTO>(Convert.ToString(response.Result));
                villaNumberVM.VillaNumber =  _mapper.Map<VillaNumberUpdateDTO>(model);
            }

            response = await _villaService.GetAllAsync<APIResponse>(await HttpContext.GetTokenAsync("access_token"));
            if (response != null && response.IsSuccess)
            {
                villaNumberVM.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>
                    (Convert.ToString(response.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    }); 
                return View(villaNumberVM);
            }


            return NotFound();
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateVillaNumber(VillaNumberUpdateVM model)
        {
            if (ModelState.IsValid)
            {

                var response = await _villaNumberService.UpdateAsync<APIResponse>(model.VillaNumber, await HttpContext.GetTokenAsync("access_token"));
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexVillaNumber));
                }
                else
                {
                    if (response.ErrorMessages.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                    }
                }
            }

            var resp = await _villaService.GetAllAsync<APIResponse>(await HttpContext.GetTokenAsync("access_token"));
            if (resp != null && resp.IsSuccess)
            {
                model.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>
                    (Convert.ToString(resp.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    }); ;
            }
            return View(model);
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteVillaNumber(int villaNo)
        {
            VillaNumberDeleteVM villaNumberVM = new();
            var response = await _villaNumberService.GetAsync<APIResponse>(villaNo, await HttpContext.GetTokenAsync("access_token"));
            if (response != null && response.IsSuccess)
            {
                VillaNumberDTO model = JsonConvert.DeserializeObject<VillaNumberDTO>(Convert.ToString(response.Result));
                villaNumberVM.VillaNumber = model;
            }

            response = await _villaService.GetAllAsync<APIResponse>(await HttpContext.GetTokenAsync("access_token"));
            if (response != null && response.IsSuccess)
            {
                villaNumberVM.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>
                    (Convert.ToString(response.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
                return View(villaNumberVM);
            }


            return NotFound();
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteVillaNumber(VillaNumberDeleteVM model)
        {

            var response = await _villaNumberService.DeleteAsync<APIResponse>(model.VillaNumber.VillaNo, await HttpContext.GetTokenAsync("access_token"));
            if (response != null && response.IsSuccess)
            {
                return RedirectToAction(nameof(IndexVillaNumber));
            }

            return View(model);
        }



    }
}

MagicVilla_API-master/MagicVilla_Web/Views/VillaNumber/CreateVillaNumber.cshtml
@model MagicVilla_Web.Models.VM.VillaNumberCreateVM

<form asp-action="CreateVillaNumber">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Create Villa</h1>
        <hr />

        <div class="row">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="VillaNumber.VillaNo" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="VillaNumber.VillaNo" class="form-control" />
                <span asp-validation-for="VillaNumber.VillaNo" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="VillaNumber.VillaID" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="VillaNumber.VillaID" class="form-select" asp-items="@Model.VillaList">
                    <option disabled selected>--Select Villa--</option>
                </select>
                <span asp-validation-for="VillaNumber.VillaID" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="VillaNumber.SpecialDetails" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="VillaNumber.SpecialDetails" class="form-control" rows="5"></textarea>
                <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger"></span>
            </div>
           
            <div class="col-5 offset-2">
                <a asp-action="IndexVillaNumber" asp-controller="VillaNumber" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MagicVilla_API-master/MagicVilla_Web/Views/VillaNumber/DeleteVillaNumber.cshtml
@model MagicVilla_Web.Models.VM.VillaNumberDeleteVM

<form asp-action="DeleteVillaNumber">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Delete Villa</h1>
        <hr />
        <input hidden asp-for="VillaNumber.VillaNo" />
        <div class="row">

            <div class="col-2">
                <label asp-for="VillaNumber.VillaNo" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="VillaNumber.VillaNo" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="VillaNumber.VillaID" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="VillaNumber.VillaID" disabled class="form-select" asp-items="@Model.VillaList">
                    <option disabled selected>--Select Villa--</option>
                </select>
            </div>
            <div class="col-2">
                <label asp-for="VillaNumber.SpecialDetails" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="VillaNumber.SpecialDetails" readonly class="form-control" rows="5"></textarea>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexVillaNumber" asp-controller="VillaNumber" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MagicVilla_API-master/MagicVilla_Web/Views/VillaNumber/IndexVillaNumber.cshtml
@model IEnumerable<MagicVilla_Web.Models.Dto.VillaNumberDTO>
<br />
<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">
			<h1 class="text-primary">Villa Number List</h1>
        </div>
        <div class="col text-end pt-1">
			<a asp-controller="VillaNumber" asp-action="CreateVillaNumber" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i> Create New Villa Number</a>
        </div>
    </div>

    <table class="table">
		<thead>
			<tr>
				<th>
					Villa Name
				</th>
				<th>
					Villa Number
				</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			@foreach(var item in Model){
				<tr>
					<td>@item.Villa.Name</td>
					<td>@item.VillaNo</td>
					<td>
						<a asp-controller="VillaNumber" asp-action="UpdateVillaNumber" asp-route-villaNo="@item.VillaNo" class="btn btn-success"><i class="bi bi-pencil-square"></i></a>
						<a asp-controller="VillaNumber" asp-action="DeleteVillaNumber" asp-route-villaNo="@item.VillaNo" class="btn btn-danger"><i class="bi bi-trash-fill"></i></a>
					</td>
				</tr>
			}
		</tbody>
    </table>

</div>

MagicVilla_API-master/MagicVilla_Web/Views/VillaNumber/UpdateVillaNumber.cshtml
@model MagicVilla_Web.Models.VM.VillaNumberUpdateVM

<form asp-action="UpdateVillaNumber">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Update Villa</h1>
        <hr />
        <input hidden asp-for="VillaNumber.VillaNo" />
        <div class="row">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="VillaNumber.VillaNo" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="VillaNumber.VillaNo" disabled class="form-control" />
                <span asp-validation-for="VillaNumber.VillaNo" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="VillaNumber.VillaID" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="VillaNumber.VillaID" class="form-select" asp-items="@Model.VillaList">
                    <option disabled selected>--Select Villa--</option>
                </select>
                <span asp-validation-for="VillaNumber.VillaID" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="VillaNumber.SpecialDetails" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="VillaNumber.SpecialDetails" class="form-control" rows="5"></textarea>
                <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexVillaNumber" asp-controller="VillaNumber" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Update" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}